# Generated by Django 5.1.7 on 2025-03-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissance', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='numéro_téléphone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
