# Generated by Django 5.1.7 on 2025-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissance', '0003_admin_email_admin_numéro_téléphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='prénom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
